apiVersion: v1
kind: Service
metadata:
  labels:
    app: starcoin-airdrop-service
  name: starcoin-airdrop-service
spec:
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 4000
  selector:
    app: starcoin-airdrop-service
  type: LoadBalancer
status:
  loadBalancer: {}
