apiVersion: apps/v1
kind: Deployment
metadata:
  name: starcoin-airdrop-service-deployment
  labels:
    app: starcoin-airdrop-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starcoin-airdrop-service
  template:
    metadata:
      labels:
        app: starcoin-airdrop-service
    spec:
      containers:
        - name: starcoin-airdrop-service
          image: starcoin/starcoin-airdrop-service:0.1.1
          env:
            - name: STARCOIN_AIRDROP_SERVICE_MYSQL_HOST
              value: "starcoin-db-2.czftx6muneg7.ap-northeast-1.rds.amazonaws.com"
            - name: STARCOIN_AIRDROP_SERVICE_MYSQL_PORT
              value: "3306"
            - name: STARCOIN_AIRDROP_SERVICE_MYSQL_DB
              value: "airdrop"
            - name: STARCOIN_AIRDROP_SERVICE_MYSQL_USER
              value: "starcoin"
            - name: STARCOIN_AIRDROP_SERVICE_MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: mysql-pwd
                  key: password
