#!/bin/bash
CURDIR=$(cd "$(dirname "$0")"; pwd)
docker run -d --name starcoin-airdrop-service -p 4000:4000 \
    -e "STARCOIN_AIRDROP_SERVICE_MYSQL_HOST=${STARCOIN_AIRDROP_SERVICE_MYSQL_HOST}" \
    -e "STARCOIN_AIRDROP_SERVICE_MYSQL_PORT=${STARCOIN_AIRDROP_SERVICE_MYSQL_PORT}" \
    -e "STARCOIN_AIRDROP_SERVICE_MYSQL_USER=${STARCOIN_AIRDROP_SERVICE_MYSQL_USER}" \
    -e "STARCOIN_AIRDROP_SERVICE_MYSQL_PWD=${STARCOIN_AIRDROP_SERVICE_MYSQL_PWD}" \
    -e "STARCOIN_AIRDROP_SERVICE_MYSQL_DB=${STARCOIN_AIRDROP_SERVICE_MYSQL_DB}" \
    -e "STARCOIN_AIRDROP_SERVICE_ADMIN=${STARCOIN_AIRDROP_SERVICE_ADMIN}" \
    starcoin/starcoin-airdrop-service:latest

docker ps


